export const CATEGORIES_ACTION_TYPE = {
  SET_CATEGORIES: "category/SET_CATEGORIES",
  FETCH_CATEGORIES_DATA_SUCESS: "category/FETCH_DATA_SUCESS",
  FETCH_CATEGORIES_DATA_STOP: "category/FETCH_DATA_START",
  FETCH_CATEGORIES_DATA_ERROR: "category/FETCH_DATA_ERROR",
};
